import time
from enum import IntEnum
import random

ENCOUNTERS = [
    [
        "The Yeti's Challenge",
        'In the snowy peaks, your hero stumbles upon a Yeti challenging travelers to a test of strength.',
        'Beat the Yeti in an arm wrestling contest',
        'Use a clever trick or item to outwit the Yeti.',
        'Success: Your hero impresses the Yeti, who grants safe passage and a valuable icy treasure.',
        'Failure: The Yeti bests your hero in the challenge, resulting in a hasty and embarrassing retreat down the mountain.',
        'To win this encounter, your hero must either:'
    ],
    [
        'The Penguin Parade Puzzle',
        'Your hero discovers a parade of penguins guarding a secret path to a hidden ice cave.',
        'Sneak past the penguins and get into the hidden ice cave without them noticing.',
        'Use a special ability or item to communicate with the penguins and gain their trust.',
        'Success: The penguins reveal the hidden path, leading to ancient artifacts and knowledge.',
        'Failure: The penguins become suspicious and block the path, leaving your hero to find another way.',
        'To win this encounter, your hero must either:'
    ],
    [
        "The Mysterious Woodcutter's Request",
        "A mysterious woodcutter in the frosty forest asks for your hero's help in a dangerous task, rescuing their pet penguin from a yeti's cave.",
        'Convince the woodcutter to move on and get a new pet, because that penguin is yeti food.',
        'Assist the woodcutter and save the penguin from the Yetis cave.',
        'Success: The woodcutter rewards your hero with rare enchanted lumber and a map to a hidden treasure.',
        'Failure: The task proves too difficult, causing an accident and leaving the hero in a difficult predicament.',
        'To win this encounter, your hero must either:'
    ],
    [
        "The Abominable Snowman's Labyrinth",
        'Your hero enters a labyrinth of ice, home to the elusive Abominable Snowman.',
        'Have a Sneakiness score higher than 12',
        "Solve the labyrinth's puzzle with an enchanted compass or clever wit.",
        'Success: Navigating the maze leads to a hidden trove of treasures and ancient lore.',
        'Failure: Getting lost in the maze results in a chilling encounter with the Snowman.',
        'To win this encounter, your hero must either:'
    ],
    [
        "The Polar Bear's Dilemma",
        'A mother polar bear blocks your path, protecting her cubs and looking for food.',
        'Have a Craftiness score higher than 9',
        'Use a food item or a distraction to safely bypass the bear family.',
        'Success: The bear allows safe passage, and your hero finds a rare ice crystal.',
        'Failure: The bear becomes aggressive, leading to a dangerous situation.',
        'To win this encounter, your hero must either:'
    ],
    [
        "The Reindeer's Request",
        "A magical reindeer asks for your hero's help in retrieving a lost mystical antler.",
        'Have a Scrappiness score higher than 9',
        'Use a special ability or item to track and recover the antler.',
        'Success: The grateful reindeer rewards your hero with a speedy journey and a protective charm.',
        'Failure: Failing to find the antler leaves your hero stranded in the cold wilderness.',
        'To win this encounter, your hero must either:'
    ],
    [
        "The Frost Giant's Game",
        'A playful Frost Giant challenges your hero to a game of wits and riddles.',
        'Have a Fabulousness score higher than 8',
        'Use charm and intelligence to outsmart the Frost Giant.',
        'Success: Winning the game earns a magical frost weapon or artifact.',
        "Failure: Losing the game incurs the Giant's laughter and a minor curse.",
        'To win this encounter, your hero must either:'
    ],
    [
        "The Ice Witch's Riddle",
        'An Ice Witch blocks your path, offering passage only to those who solve her riddle.',
        'Have a Craftiness score higher than 8',
        'Decipher the riddle using knowledge or a mystical item.',
        'Success: Solving the riddle reveals a shortcut and a potion of frost resistance.',
        'Failure: Incorrect answers result in a temporary freeze spell.',
        'To win this encounter, your hero must either:'
    ],
    [
        "The Snow Owl's Secret",
        'A mystical snow owl offers to guide your hero to a hidden shrine, but at a price.',
        'Have a Fabulousness score higher than 14',
        'Perform a dance or song to entertain the owl.',
        'Success: The owl leads to a shrine with ancient wisdom and artifacts.',
        'Failure: A displeased owl leads your hero astray, causing delays and hardships.',
        'To win this encounter, your hero must either:'
    ],
    [
        "The Frozen Fortress",
        "Your hero discovers a massive fortress encased in ice, guarded by mystical frost creatures.",
        "Use an ability or item to overcome the freezing barrier and enter the fortress.",
        "Inside, navigate a blizzard maze created by an ancient winter spell.",
        "Success: Your hero infiltrates the heart of the fortress, finding a legendary ice artifact.",
        "Failure: If unable to penetrate the ice or lost in the maze, your hero faces hypothermia.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Icy Serpent's Lair",
        "In a secluded icy cave, your hero encounters a giant serpent made entirely of ice.",
        "Use an ability or item to resist the serpent's chilling breath and icy scales.",
        "Find a way to melt or break through the serpent's protective layer of ice.",
        "Success: Defeating the serpent reveals a cache of frozen treasures and rare gems.",
        "Failure: Failing to resist or break the ice results in being frozen in the serpent's lair.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Snow Witch's Enigma",
        "Your hero encounters a mysterious Snow Witch, who challenges them with enigmatic tasks.",
        "Use an ability or item to solve the witch's complex ice puzzle, unlocking the path forward.",
        "Brave the witch's enchanted blizzard, finding a way through the violent snowstorm.",
        "Success: Outwitting the witch grants access to her library of arcane knowledge.",
        "Failure: Failure to solve the puzzle or withstand the blizzard results in a frostbound curse.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Lost Parcel",
        "Your hero encounters a member of the Penguin Post who has lost a vital parcel in a snowstorm.",
        "Use an ability or item to track and retrieve the lost parcel in the blinding snow.",
        "Protect the Penguin Post member from a band of thieving arctic foxes.",
        "Success: The parcel is safely returned, earning your hero a rare stamp of gratitude from Penguin Post.",
        "Failure: The parcel remains lost, or the foxes succeed in their thievery.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "The Icy Relay Race",
        "Your hero is invited to participate in Penguin Post's annual icy relay race.",
        "Use speed and agility to navigate the treacherous icy track without falling.",
        "Assist a lagging Penguin Post member in delivering a time-sensitive package.",
        "Success: Winning the race grants a special badge of honor and a speedy mount from Penguin Post.",
        "Failure: Falling behind or failing to deliver the package on time disappoints the penguins.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "The Frozen Ink Mystery",
        "A Penguin Post member seeks help with a batch of letters written in mysteriously frozen ink.",
        "Use a magical ability or item to decipher the frozen ink without damaging the letters.",
        "Safely deliver the deciphered letters to their intended recipients across the icy landscape.",
        "Success: Unraveling the mystery of the frozen ink reveals a hidden message and a secret reward.",
        "Failure: The letters remain unreadable or get lost during delivery.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "The Crystal Caper",
        "Your hero stumbles upon ice raccoons attempting to steal a luminescent crystal from a frosty cavern.",
        "Use an ability or item to outsmart the raccoons and secure the crystal.",
        "Navigate the treacherous cavern terrain without alerting the raccoon sentinels.",
        "Success: Securing the crystal grants your hero its icy power and the raccoons' respect.",
        "Failure: The raccoons outwit your hero, leading to a cold and embarrassing retreat.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "The Ice Raccoon's Feast",
        "Your hero discovers the ice raccoons' secret feast, full of enchanted food and guarded by the colony.",
        "Use a disguise or charm to participate in the feast without arousing suspicion.",
        "Help solve a dispute among the raccoons over the distribution of the feast's delicacies.",
        "Success: The raccoons welcome your hero as an honorary member, sharing magical food.",
        "Failure: Being discovered or failing the task leads to a chase out of the feast.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "The Raccoon's Ice Labyrinth",
        "The ice raccoons challenge your hero to navigate their icy labyrinth to find a hidden treasure.",
        "Use keen observation and intelligence to solve the labyrinth's puzzles and traps.",
        "Face and befriend the guardian of the treasure, an ancient raccoon spirit.",
        "Success: Overcoming the labyrinth earns a mystical artifact guarded by the raccoons.",
        "Failure: Getting lost or failing the challenge results in a frosty misadventure.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "The Frost Faerie's Invitation",
        "A Frost Faerie invites your hero to an exclusive tea party in a hidden glacial grotto.",
        "Use an ability or item to navigate to the hidden glacial grotto.",
        "Use an ability or item to present a unique and worthy gift to the Frost Faerie.",
        "Success: Finding and gaining entry to the party rewards your hero with faerie alliances.",
        "Failure: Failure to find the grotto or impress the Faerie results in a chilly reception.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "The Victorian Frost Fair",
        "Traveling to Victorian times, your hero arrives at a frost fair on the frozen Thames.",
        "Use an ability or item to blend in with the crowd and gather crucial temporal clues.",
        "Use an ability or item to prevent a villain from using the fair to disrupt the time stream.",
        "Success: Thwarting the villain preserves history and endears your hero to Victorian society.",
        "Failure: The villain's plot causes historical ripples, affecting the present.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "The Seal Symphony",
        "Your hero is tasked with orchestrating a musical performance by a group of talented seals.",
        "Use a musical instrument or a sound-based ability to conduct the seals in harmony.",
        "Solve a puzzle involving matching the seals' rhythms to open a hidden ice cavern.",
        "Success: The symphony mesmerizes the parade audience, and the cavern reveals rare treasures.",
        "Failure: Discordant music leads to chaos, and the cavern remains sealed.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "The Penguin's Lost Costume",
        "You enter a cavern and find a colony of circus penguins that are beginning a parade. You see a penguin performer crying because they lost their costume, crucial for the parade's finale.",
        "Use tracking skills or a locating spell to find the missing costume.",
        "Design a backup costume using available materials as a creative solution.",
        "Success: The penguin shines in the finale, and your hero is hailed as a parade savior.",
        "Failure: The penguin's absence dims the parade's spirit, leading to a lackluster finale.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "The Ice Sculpting Challenge",
        "Your hero enters an ice sculpting contest against skilled artists and magical beings.",
        "Use artistic skills or a magical ice-carving tool to create a stunning sculpture.",
        "Convince a panel of enchanted creatures to vote for your hero's sculpture.",
        "Success: Winning the contest earns a magical ice artifact with unique properties.",
        "Failure: A less impressive sculpture results in a humorous, but icy mishap.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "The Magical Hot Chocolate Quest",
        "A quest to find the ingredients for a magical hot chocolate that grants wishes.",
        "Use survival skills or a potion to withstand the cold while gathering rare ingredients.",
        "Brew the hot chocolate perfectly to unlock its wish-granting powers.",
        "Success: A perfect brew grants a wish, offering a boon to your hero.",
        "Failure: An imperfect brew leads to unpredictable and whimsical effects.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "The Krampus Confrontation",
        "Your hero faces Krampus, the fearsome Christmas demon, in a desolate snowy landscape.",
        "Use a powerful artifact or combat ability to duel Krampus in a battle of strength and wits.",
        "Rescue captured children from Krampus's sack while evading his deadly grasp.",
        "Success: Defeating Krampus frees the children and earns a legendary Christmas artifact.",
        "Failure: Losing the battle results in the hero being taken by Krampus, never to be seen again.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "The Cursed Sleigh Ride",
        "A cursed sleigh, driven by ghostly reindeer, threatens to unleash eternal winter.",
        "Use a combination of agility and a magic spell to gain control of the sleigh.",
        "Dispel the curse before the sleigh crashes into a mountain, ending the ride and the hero's life.",
        "Success: Controlling the sleigh and lifting the curse saves the world from endless winter.",
        "Failure: A crash results in a catastrophic explosion, dooming the hero and the surrounding area.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "The Frost Giant's Ultimatum",
        "A Frost Giant threatens a town with a devastating blizzard if his demands are not met.",
        "Use strategic thinking and a powerful weapon to challenge and defeat the Frost Giant.",
        "Negotiate with the Giant to spare the town, risking the hero's life in the process.",
        "Success: Defeating or persuading the Giant saves the town and brings a heroic legacy.",
        "Failure: Failing the challenge results in the town's destruction and the hero's demise.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "Santa's Doomed Workshop",
        "Santa's workshop is under siege by a coalition of nefarious winter witches.",
        "Use combat skills or a magical shield to defend the workshop from the witches' attack.",
        "Rescue Santa and his elves trapped in a powerful enchantment spell.",
        "Success: Saving Santa's workshop preserves the spirit of Christmas worldwide.",
        "Failure: Failing to defend the workshop or save Santa leads to a world without Christmas joy.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "The Snow Queen's Wrath",
        "The Snow Queen casts a spell to plunge the world into a never-ending blizzard.",
        "Use a legendary sword or a weather-altering artifact to confront and battle the Snow Queen.",
        "Solve an intricate ice puzzle to deactivate the source of the eternal blizzard.",
        "Success: Defeating the Snow Queen and stopping the blizzard saves countless lives.",
        "Failure: Losing to the Queen or failing the puzzle results in a frozen apocalypse.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "The Reindeer Rebellion",
        "Santa's reindeer, led by a rogue Rudolph, rebel and threaten to disrupt Christmas Eve.",
        "Use persuasive abilities or a calming potion to quell the rebellion among the reindeer.",
        "Safely guide Santa's sleigh through a treacherous storm created by the rebellious reindeer.",
        "Success: Pacifying the reindeer and guiding the sleigh ensures Christmas is saved.",
        "Failure: Failing to calm the reindeer or navigate the storm leads to a tragic Christmas disaster.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "The Golem's Rampage",
        "A mystical Golem, created to protect Hanukkah, has gone rogue and threatens the celebration.",
        "Use ancient scrolls or mystical knowledge to understand the Golem's true purpose.",
        "Devise a strategy using a powerful artifact to calm the Golem without destroying it.",
        "Success: The Golem is pacified, safeguarding Hanukkah and earning the hero a legendary relic.",
        "Failure: Failing to calm the Golem results in widespread destruction and the loss of Hanukkah's spirit.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "The Lost Dreidel of Fate",
        "A powerful Dreidel capable of altering reality is lost in a labyrinth of ice.",
        "Navigate the labyrinth using wisdom and resilience to find the Dreidel.",
        "Play a high-stakes game with the Dreidel against a mystical adversary.",
        "Success: Winning the game wields the power of the Dreidel to bring peace and prosperity.",
        "Failure: Losing the game results in dire consequences, altering the fabric of reality.",
        "To win this encounter, your hero must complete both of the following:",
    ],
    [
        "The Great Penguin Exhibition",
        "Your party arrives at a lively penguin play party, where a grand exposition is about to start.",
        "Help organize the event by using your skills or abilities to pair up penguins into groups.",
        "Create a dazzling display of lights or perform a dance to entertain the penguins as they celebrate.",
        "Success: The play party is a hit, earning your party accolades and a special penguin gift.",
        "Failure: Disorganization or a lackluster performance leads to a forgettable play party.",
        "To win this encounter, your party must successfully complete both of the following tasks:",
    ],
    [
        "The Penguin Feast",
        "The penguins invite your party to a grand feast, but there's a catch: you must help prepare it.",
        "Use culinary skills or a magical cooking utensil to prepare a delicious seafood dish.",
        "Entertain the penguins with stories or songs while they enjoy the feast.",
        "Success: Delighting the penguins with your cooking and entertainment earns a magical penguin totem.",
        "Failure: A poor dish or dull entertainment results in a polite, but quick, end to the feast.",
        "To win this encounter, your party must successfully complete both of the following tasks:",
    ],
    [
        "The Slippery Slide Race",
        "Penguins challenge your party to a race down a massive, icy slide.",
        "Use agility or magical aid to navigate the twists and turns of the slide.",
        "At the bottom, you splash into the water only do discover something horrible... Sharks!  Escape from the sharks without being eaten.",
        "Success: Winning the race grants your party a trophy made of pure ice.",
        "Failure: Losing the race results in a humorous tumble into a snowbank or being eaten alive by sharks.",
        "To win this encounter, your party must successfully complete both of the following tasks:",
    ],
    [
        "The Snow Goblin",
        "You stumble upon a small shack in the snow and a goblin comes out, singing Jingle Bell Rock. I am so sick of all these overpowered adventurers coming through with their special powers, crushing all my friends and family. Do you have special powers or are you a nice kind silly goblin friend?",
        "Show the goblin your powers to prove you are not overpowered.",
        "Destroy the goblin with your great powers and take their loot",
        "Show you are not OP: Prove you are not like the others and the Snow Goblin gives you a freeze dried potato snack to take to her griffin buddy up the mountain. Go there and fly anywhere.",
        "Failure: If you are OP, the goblin will ignore you. If you crush the goblin, the Griffin will swoop down and attack with Powerful Shrieking attacks. The goblin has no treasure.",
        "Choose your path:",
    ],







    # [
    #     "The Drunken Innkeeper",
    #     "Your hero stops at an inn for the night and meets the rather drunken innkeeper. The innkeeper starts making judgey comments about your heroes' outfit.",
    #     "Have a Fabulousness score higher than 15",
    #     "Use an ability or item that can diffuse the situation without injuring the innkeeper.",
    #     "If you succeed in one of those, then you are able to diffuse the situation and book your room for the night.",
    #     "Otherwise, you get too upset at that innkeeper and punch them in the face. The town sheriff sees this and arrests you. You fail the encounter and spend the night in jail.",
    #     "To win this encounter, your hero must either:",
    # ],
    [
        "The Slippery Bridge",
        "Your party comes across a rickety old bridge over a deep ravine. The bridge looks dangerous to cross.",
        "Have a Sneakiness score higher than 13",
        "Use an ability or item to help you maintain balance while crossing the bridge.",
        "If you succeed, you make it across the bridge without incident and continue on your journey.",
        "Otherwise, you lose your footing and fall into the ravine below. You take significant damage and your party must use healing resources to revive you before continuing on your journey.  If you have no healing resources then you die.",
        "To win this encounter, your hero must either:",
    ],
    # [
    #     "The Mischievous Imp",
    #     "Your party enters a dark and creepy cave. Suddenly, you hear giggling and the sound of something running away. An imp appears and begins playing pranks on your party.",
    #     "Have a Craftiness score higher than 11",
    #     "Use an ability to outsmart the imp and catch it.",
    #     "If you succeed, you catch the imp and are able to continue on your journey without further incident.",
    #     "Otherwise, the imp continues to play pranks on your party, distracting and delaying you. Your party loses valuable time and resources as a result.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Bridge Troll",
    #     "Your party comes upon a rickety bridge guarded by a troll. The troll demands a toll to cross.",
    #     "Pay the toll or have a Fabulousness score higher than 13 to talk your way across.",
    #     "Use an ability or item to trick or distract the troll.",
    #     "If you succeed in one of those, then you are able to cross the bridge.",
    #     "Otherwise, the troll attacks your party. You fail the encounter and must fight the troll.  The troll eats your pet salamander.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Enchanted Forest",
    #     "Your party enters a beautiful and lush forest, but you quickly realize something is amiss. The trees seem to be moving and shifting around you, and you hear whispers in the wind.",
    #     "Have a Fabulousness score higher than 16 to understand the magical nature of the forest.",
    #     "Use an ability or item to navigate the enchanted forest.",
    #     "If you succeed in one of those, then you are able to safely navigate the forest.",
    #     "Otherwise, your party becomes lost and disoriented in the forest. You fail the encounter and must find your way out before nightfall.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Locked Chest",
    #     "Your party comes across a locked chest on the side of the road. There is no sign of the owner.",
    #     "Have a Scrappiness score higher than 14 to break it open.",
    #     "Use an ability or item to pick the lock.",
    #     "If you succeed, the chest opens revealing some treasure.",
    #     "Otherwise, you can't pick the lock and must move on.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Haunted House",
    #     "Your party comes across a seemingly abandoned house with strange noises coming from inside.",
    #     "Have a Scrappiness score higher than 16 to force the door open.",
    #     "Use an ability or item to break down the door.",
    #     "If you succeed, you enter the house and can investigate.",
    #     "Otherwise, you can't break down the door and must move on.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Lost Key",
    #     "Your party arrives at a mysterious dungeon and finds the door locked. A nearby note says 'The key is lost in the nearby woods'.",
    #     "Have a Fabulousness score higher than 13 to find the key.",
    #     "Use an ability or item to pick the lock",
    #     "If you succeed, you find the key and unlock the door to continue your adventure.",
    #     "Otherwise, you are unable to find the key and must turn back. You fail the encounter and lose valuable time.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Poisoned Water",
    #     "Your party reaches a river blocking your path. The water is poisonous and will damage anyone who tries to cross.",
    #     "Have a Scrappiness score higher than 11",
    #     "Use an ability or item to purify the water",
    #     "If you succeed, you successfully purify the water and can cross without taking damage.",
    #     "Otherwise, you take damage from the poisonous water and lose valuable time. You fail the encounter and must find another way around.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Trapped Chest",
    #     "Your party discovers a treasure chest sitting alone in a room. But as you approach it, you notice a tripwire on the ground.",
    #     "Have a Scrappiness score higher than 14",
    #     "Use an ability or item to disarm the trap",
    #     "If you succeed, you safely disarm the trap and open the chest to discover its treasures.",
    #     "Otherwise, you trigger the trap and take damage from the explosion. You fail the encounter and lose valuable time.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Charlatan",
    #     "Your party comes across a charismatic salesman who is selling potions that promise incredible results.",
    #     "Have a Fabulousness score higher than 13",
    #     "Use an ability or item to identify the authenticity of the potions",
    #     "If you succeed, you realize the potions are fake and avoid wasting your gold.",
    #     "Otherwise, you purchase the fake potions and suffer negative effects. You fail the encounter and lose valuable gold.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Haunted Mansion",
    #     "Your party stumbles upon an abandoned mansion with a dark history. As you enter, the doors shut behind you and the lights flicker.",
    #     "Have a Craftiness score higher than 12",
    #     "Use an ability or item to dispel the ghosts haunting the mansion",
    #     "If you succeed, you dispel the ghosts and can continue exploring the mansion.",
    #     "Otherwise, the ghosts attack your party and you must flee the mansion. You fail the encounter and lose valuable time.",
    #     "To win this encounter, your hero must either:",
    # ],
    [
        "The Bridge Troll",
        "Your party reaches a bridge guarded by a troll who demands a toll for crossing.",
        "Have a Fabulousness score higher than 11",
        "Use an ability or item to persuade the troll to let you pass for free",
        "If you succeed, the troll is convinced and you can cross the bridge without paying the toll.",
        "Otherwise, you must pay the toll or fight the troll. You fail the encounter and lose your gold.",
        "To win this encounter, your hero must either:",
    ],
    # [
    #     "The Labyrinth",
    #     "Your party enters a labyrinth with confusing twists and turns. The walls look the same and it's easy to get lost.",
    #     "Have a Craftiness score higher than 16",
    #     "Use an ability or item to navigate the labyrinth without getting lost",
    #     "If you succeed, you successfully navigate the labyrinth and find the exit.",
    #     "Otherwise, you get lost in the labyrinth and waste valuable time. You fail the encounter and must try again.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Sneaky Thief",
    #     "As your party makes their way through a crowded market, you suddenly feel a hand in your pocket. A pickpocket is trying to steal your valuables.",
    #     "Have a Sneakiness higher than 16 to catch the thief in the act and retrieve your valuables.",
    #     "Use an ability or item to track down the thief and retrieve your stolen valuables.",
    #     "If you succeed, you catch the thief and retrieve your stolen valuables. You can continue your journey with all your belongings intact.",
    #     "If you fail, the thief escapes with your valuables and you are left empty-handed. Lose all your items.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Tricky Puzzle",
    #     "Your party enters a room with a large locked door. To proceed, you must solve a complex puzzle.",
    #     "Have a Craftiness higher than 14 to solve the puzzle.",
    #     "Use an ability or item to decipher the clues and solve the puzzle.",
    #     "If you succeed, you solve the puzzle and the door unlocks, allowing you to continue your journey.",
    #     "If you fail, you are unable to solve the puzzle and are stuck in the room.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Intimidating Opponent",
    #     "Your party encounters a group of bandits blocking your path. Their leader steps forward and challenges you to a one-on-one fight.",
    #     "Roll a Scrappiness check higher than 16 to defeat the bandit leader in combat.",
    #     "Use an ability or item to gain an advantage in the fight against the bandit leader.",
    #     "If you succeed, you defeat the bandit leader and the rest of the bandits flee. You can continue on your journey without further interruption.",
    #     "If you fail, the bandit leader defeats you and takes all your belongings. You wake up later, battered and bruised, with nothing but the clothes on your back.",
    #     "To win this encounter, your hero must either:",
    # ],
    [
        "The Guarded Door",
        "Your hero comes across a heavily guarded door that appears to be locked. The guards tell your hero that they cannot enter without the proper clearance.",
        "Have a Craftiness higher than 15 to create a convincing forgery of the clearance documents.",
        "Use an ability or item to persuade the guards to let your hero through.",
        "If you succeed in one of those, then you are able to enter through the door.",
        "Otherwise, the guards deny your hero entry, and your hero must find another way around.",
        "To win this encounter, your hero must either:",
    ],
    [
        "The Raging River",
        "Your hero comes across a raging river that is too wide and deep to cross on foot. There are no bridges or boats in sight.",
        "Have a Scrappiness higher than 14 to build a raft from nearby materials.",
        "Use an ability or item to swim across the river safely.",
        "If you succeed in one of those, then you are able to cross the river.",
        "Otherwise, your hero will be swept away by the river dies.",
        "To win this encounter, your hero must either:",
    ],
    # [
    #     "The Locked Chest",
    #     "Your hero comes across a locked chest that appears to be of great value. The lock on the chest is quite complex.",
    #     "Have a Sneakiness higher than 16 to pick the lock.",
    #     "Use an ability or item to break the lock and open the chest.",
    #     "If you succeed in one of those, then you are able to open the chest and see what's inside.",
    #     "Otherwise, your hero is unable to open the chest, and the valuable contents remain a mystery.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Intimidating Thug",
    #     "Your hero encounters a tough-looking thug who demands payment for passage through the area.",
    #     "Have a Fabulousness higher than 13 to dazzle the thug with your hero's wealth and status.",
    #     "Use an ability or item to intimidate the thug and scare them away.",
    #     "If you succeed in one of those, then your hero can pass through the area without further trouble.",
    #     "Otherwise, the thug will demand payment or even attack your hero, leading to a difficult fight or a loss of valuable items.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Locked Chest",
    #     "Your hero comes across a locked chest on their journey. It seems to be protected by a magical barrier. Your hero can either try to force it open or attempt to dispel the magic.",
    #     "Have a Craftiness score higher than 16 to dispel the magic",
    #     "Use an ability or item to pick the lock or break it open",
    #     "If you succeed in opening the chest, you find a valuable item inside.",
    #     "If you fail, the chest explodes and deals damage to your hero.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Dark Forest",
    #     "Your hero finds themselves lost in a dark forest. They hear the sound of growling and rustling in the bushes. Your hero must either sneak past the creatures or fight them head-on.",
    #     "Have a Sneakiness score higher than 14 to sneak past the creatures",
    #     "Use an ability or item to sneak past the creatures",
    #     "If you succeed in sneaking past, you make it out of the forest unscathed.",
    #     "If you fail, the creatures attack and kill your hero.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Cliffside",
    #     "Your hero is traveling along a cliffside path when they come across a narrow bridge. The bridge is old and rickety, and there's a large gap between the planks. Your hero can either try to cross the bridge carefully or attempt to jump across the gap.",
    #     "Have a Scrappiness score higher than 15 to make the jump",
    #     "Use an ability or item to cross the bridge",
    #     "If you succeed in crossing the bridge, you make it safely to the other side.",
    #     "If you fail, you fall into the gap and die.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Royal Ball",
    #     "Your hero is invited to a grand royal ball. The king is looking for a new advisor, and your hero hopes to be chosen. Your hero can either try to impress the king with their Fabulousness or attempt to sabotage the other candidates.",
    #     "Have a Fabulousness score higher than 17 to impress the king",
    #     "Use an ability or item to sabotage the other candidates",
    #     "If you succeed in impressing the king, you are chosen as the new advisor and gain a powerful ally.",
    #     "If you fail, the other candidates are chosen, and you lose favor with the king.",
    #     "To win this encounter, your hero must either:",
    # ],
    [
        "The Goblin Lair",
        "Your hero stumbles upon a goblin lair. The goblins are hoarding a valuable treasure, but they won't part with it easily. Your hero can either try to negotiate with the goblins or fight them for the treasure.",
        "Have a Craftiness score higher than 14 to negotiate with the goblins",
        "Use an ability or item to fight the goblins",
        "If you succeed in negotiating, the goblins part with the treasure, and your hero gains a valuable item.",
        "If you fail, the goblins attack, and your hero takes damage.",
        "To win this encounter, your hero must either:",
    ],
    # [
    #     "The Scam Artist",
    #     "Your hero gets approached by a street vendor selling a seemingly rare and valuable item. However, upon closer inspection, the item is clearly a fake.",
    #     "Have a Scrappiness score higher than 15 to see through the vendor's scam and haggle them down to a fair price.",
    #     "Use an ability or item to convince the vendor to sell the item at a lower price.",
    #     "If you succeed in one of those, then you obtain the item at a reasonable price.",
    #     "Otherwise, you end up paying too much for the fake item and the vendor laughs all the way to the bank.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Persuasive Politician",
    #     "Your hero attends a political rally where they are approached by a charismatic politician who is trying to win over voters. The politician's speech is full of logical fallacies, but many in the crowd are convinced by their charm.",
    #     "Have a Fabulousness score higher than 13 to deliver a counter-argument that wins over the crowd.",
    #     "Use an ability or item to distract the crowd from the politician's speech.",
    #     "If you succeed in one of those, then you successfully sway the crowd to your side.",
    #     "Otherwise, the politician's charm wins out and you are drowned out by the cheers of their supporters.",
    #     "To win this encounter, your hero must either:",
    # ],
    [
        "The Secret Society",
        "Your hero stumbles upon a secret society that is known for their exclusive membership and their strict initiation process. They are suspicious of outsiders and only allow those who can prove their worth to join.",
        "Have a Craftiness score higher than 15 to solve the society's initiation challenge.",
        "Use an ability or item to bribe one of the society's members to vouch for you.",
        "If you succeed in one of those, then you are able to join the society and gain access to their resources.",
        "Otherwise, you are seen as unworthy and are kicked out of the society without any further information.",
        "To win this encounter, your hero must either:",
    ],
    [
        "The Sleeping Dragon",
        "Your hero comes across a dragon that is fast asleep in their lair. The dragon is blocking the path your hero needs to take, but waking the dragon could mean certain death.",
        "Have a Sneakiness score higher than 16 to sneak past the dragon without waking it up.",
        "Use an ability or item to distract the dragon and create a path to walk through.",
        "If you succeed in one of those, then you are able to get past the dragon without any trouble.",
        "Otherwise, the dragon wakes up and attacks you, causing a catastrophic failure.",
        "To win this encounter, your hero must either:",
    ],
    # [
    #     "The Locked Chest",
    #     "Your hero comes across a locked chest. It looks like it could contain some valuable loot. ",
    #     "Have a Craftiness score higher than 5 to pick the lock.",
    #     "Use an ability or item to break the lock.",
    #     "If you succeed, you open the chest and find some valuable treasure inside.",
    #     "Otherwise, you fail to open the chest and attract some unwanted attention. You will have to fight off the guards to escape.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Puzzling Riddle",
    #     "Your hero encounters a wise old sage who challenges them to solve a riddle.",
    #     "Have a Craftiness score higher than 13 to solve the riddle.",
    #     "Use an ability or item to ask for help.",
    #     "If you succeed, the sage rewards you with a powerful item.",
    #     "Otherwise, the sage mocks you for your lack of intelligence and you lose some self-esteem.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Angry Beast",
    #     "Your hero stumbles upon an angry beast that is blocking your path.",
    #     "Have a Scrappiness score higher than 15 to defeat the beast in combat.",
    #     "Use an ability or item to distract or pacify the beast.",
    #     "If you succeed, the beast calms down and you can continue on your journey.",
    #     "Otherwise, the beast attacks and injures you, forcing you to rest and recover before continuing.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Devious Trap",
    #     "Your hero comes across a devious trap that could injure or kill them if triggered.",
    #     "Have a Scrappiness score higher than 5 to disarm the trap.",
    #     "Use an ability or item to disable the trap.",
    #     "If you succeed, you avoid the trap and continue on your journey safely.",
    #     "Otherwise, the trap triggers and you suffer some injuries, delaying your journey.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Persuasive Merchant",
    #     "Your hero encounters a persuasive merchant who is trying to sell them some overpriced goods.",
    #     "Have a Fabulousness score higher than 13 to haggle and get a better price.",
    #     "Use an ability or item to charm or distract the merchant.",
    #     "If you succeed, you get a good deal on some valuable items.",
    #     "Otherwise, you end up paying too much and feel like you got ripped off.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Lost Key",
    #     "Your hero needs to unlock a door to proceed, but the key has been lost. You see a small hole in the wall next to the door.",
    #     "Have a Craftiness score higher than 12 to fashion a makeshift key out of nearby materials.",
    #     "Use an ability or item to pick the lock.",
    #     "If you succeed in one of those, you are able to unlock the door and proceed. Otherwise, you are unable to unlock the door and must find another way around.",
    #     "If you try to force the door open, the noise alerts nearby guards and they catch you. You fail the encounter and are captured.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Angry Shopkeeper",
    #     "Your hero enters a store to purchase an item, but the shopkeeper is extremely angry about something and is not willing to sell anything.",
    #     "Have a Fabulousness score higher than 12 to convince the shopkeeper that you have something they want to trade.",
    #     "Use an ability or item to calm the shopkeeper down.",
    #     "If you succeed in one of those, you are able to make your purchase and leave. Otherwise, the shopkeeper refuses to sell you anything and you have to leave the store empty-handed.",
    #     "If you try to steal the item, the shopkeeper catches you and alerts the authorities. You fail the encounter and are arrested.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Tightrope",
    #     "Your hero needs to cross a wide ravine to reach the other side. There is a tightrope stretched across the ravine, but it is old and unstable.",
    #     "Have a Scrappiness score higher than 15 to repair the tightrope enough to safely cross.",
    #     "Use an ability or item to stabilize the tightrope.",
    #     "If you succeed in one of those, you are able to cross the tightrope and reach the other side. Otherwise, you lose your balance and fall into the ravine, taking damage and having to find another way around.",
    #     "If you try to cross the tightrope without repairing or stabilizing it, the tightrope breaks and you fall into the ravine, taking severe damage. You fail the encounter and have to find another way around.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Persuasive Bandit",
    #     "Your hero is stopped by a bandit who demands all of your gold in exchange for passage through their territory.",
    #     "Have a Fabulousness score higher than 14 to convince the bandit that you are a powerful figure and not worth robbing.",
    #     "Use an ability or item to intimidate the bandit into letting you pass.",
    #     "If you succeed in one of those, you are able to pass through the bandit's territory unscathed. Otherwise, the bandit takes all of your gold and you have to find another way around.",
    #     "If you try to fight the bandit, they are more skilled than you expected and you are defeated. You fail the encounter and are left beaten and robbed.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Over-Enthusiastic Salesperson",
    #     "Your hero encounters an over-enthusiastic salesperson trying to sell a ridiculous item. The salesperson won't take no for an answer and keeps talking and talking.",
    #     "Have a Scrappiness score higher than 11 to intimidate the salesperson into leaving.",
    #     "Use an ability or item to distract the salesperson and slip away.",
    #     "If you succeed in one of those, then you are able to get away from the salesperson and continue on your journey.",
    #     "Otherwise, the salesperson talks your ear off and you waste valuable time. You fail the encounter and lose 1 hour.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Dancing Bear",
    #     "Your hero comes across a dancing bear in the forest. The bear is dancing to music and doesn't seem to be aggressive.",
    #     "Have a Fabulousness score higher than 13 to join in on the dancing and impress the bear.",
    #     "Use an ability or item to calm the bear down and avoid any confrontation.",
    #     "If you succeed in one of those, then you are able to continue on your journey without any harm.",
    #     "Otherwise, the bear becomes angry and attacks you. You fail the encounter and the bear eats you.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Disappearing Stairs",
    #     "Your hero comes across a staircase across a gap that seems to disappear as soon as you step on it. The staircase reappears as soon as you step off of it.",
    #     "Have a Sneakiness score higher than 14 to navigate the staircase and make it to the other side.",
    #     "Use an ability or item to create a bridge across the gap and avoid the staircase altogether.",
    #     "If you succeed in one of those, then you are able to continue on your journey without any harm.",
    #     "Otherwise, you fall into the gap and die.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Talking Tree",
    #     "Your hero encounters a talking tree in the forest. The tree is quite chatty and has a lot of stories to tell.",
    #     "Have a Craftiness score higher than 11 to keep the conversation going and gain valuable information.",
    #     "Use an ability or item to make the tree fall asleep and continue on your journey.",
    #     "If you succeed in one of those, then you are able to continue on your journey with some new knowledge.",
    #     "Otherwise, the tree talks your ear off and you waste valuable time. You fail the encounter and regret talking to a tree.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Punny Jester",
    #     "Your hero comes across a jester who tells terrible puns. The jester won't stop telling puns and seems to be enjoying themself.",
    #     "Have a Fabulousness score higher than 13 to appreciate the puns and make the jester happy.",
    #     "Use an ability or item to distract the jester and slip away.",
    #     "If you succeed in one of those, then you are able to continue on your journey without any harm.",
    #     "Otherwise, the jester tells more and more puns until you can't take it anymore. You fail the encounter and lose an hour of your life.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Spilled Soup",
    #     "Your hero is in a fancy restaurant and the waiter accidentally spills hot soup all over their lap. The waiter is mortified and doesn't know what to do.",
    #     "Have a Scrappiness score higher than 11 to quickly clean up the mess and gain the waiter's admiration.",
    #     "Use an ability or item to distract the waiter and slip away without being noticed.",
    #     "If you succeed in either of those, then you can enjoy the rest of your meal without any further interruptions.",
    #     "Otherwise, the waiter continues to apologize profusely and your hero is forced to leave the restaurant with a stained outfit and ego.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Hairy Beast",
    #     "Your hero stumbles upon a creature with long shaggy fur blocking their path. It seems friendly but it's shedding hair all over the place.",
    #     "Have a Fabulousness score higher than 13 to groom the creature and make it presentable.",
    #     "Use an ability or item to distract the creature and sneak past it.",
    #     "If you succeed in either of those, then you can continue on your way.",
    #     "Otherwise, the creature sheds even more fur on your hero and you have to spend the rest of the day picking hair off your clothes.",
    #     "To win this encounter, your hero must either:",
    # ],
    [
        "The Endless Staircase",
        "Your hero comes across a seemingly endless staircase that stretches into the clouds. There's no way to tell where it leads.",
        "Have a Craftiness score higher than 15 to fashion a parachute out of available materials and safely glide down to the bottom.",
        "Use an ability or item to conjure a magical bridge that spans the distance.",
        "If you succeed in either of those, then you can safely reach the bottom and continue on your journey.",
        "Otherwise, your hero tumbles down the stairs and lands at the bottom with a bruised bottom and ego.",
        "To win this encounter, your hero must either:",
    ],
    # [
    #     "The Haunted Mansion",
    #     "Your hero comes across a spooky old mansion that seems abandoned. But upon closer inspection, there are signs of life inside.",
    #     "Have a Sneakiness score higher than 13 to sneak past the ghostly guardians and find a way inside.",
    #     "Use an ability or item to cast a spell of invisibility and bypass the guards undetected.",
    #     "If you succeed in either of those, then you can explore the mansion and uncover its secrets.",
    #     "Otherwise, the ghostly guardians catch your hero and make them spend the night in the mansion's haunted dungeon.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Cheesy Salesman",
    #     "Your hero is browsing the market when they come across a cheese salesman who insists on offering them samples of every type of cheese imaginable.",
    #     "Have a Scrappiness score higher than 16 to politely decline the cheese and make a quick getaway.",
    #     "Use an ability or item to distract the salesman and sneak away without being noticed.",
    #     "If you succeed in either of those, then you can escape the cheesy salesman's clutches.",
    #     "Otherwise, your hero is force-fed so much cheese that they have to spend the rest of the day lactose intolerant and in pain.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Fashion Disaster",
    #     "Your hero comes across a fashion show where everyone is dressed in the latest trend. Unfortunately, your hero is still wearing their pajamas. The fashion police are now after your hero!",
    #     "Have a Fabulousness score higher than 14 to convince the fashion police that your pajamas are the new trend.",
    #     "Use an ability or item to create a distraction and escape the fashion police.",
    #     "If you succeed in one of those, you manage to get away without getting arrested for fashion crimes.",
    #     "Otherwise, the fashion police catch up to you and fine you for being a fashion disaster.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Singing Bard",
    #     "Your hero walks into a tavern and sees a bard singing a terrible song. The patrons are not amused, but the bard keeps singing anyway.",
    #     "Have a Fabulousness score higher than 13 to charm the patrons and convince them that the bard is actually talented.",
    #     "Use an ability or item to silence the bard and spare everyone from the terrible singing.",
    #     "If you succeed in one of those, the patrons are impressed with your hero's actions.",
    #     "Otherwise, the bard continues to sing, and the patrons start throwing things at your hero for not doing anything about it.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Hungry Hobbit",
    #     "Your hero meets a hungry hobbit on the road who offers to trade some valuable information for a meal.",
    #     "Have a Scrappiness score higher than 13 to scavenge enough food for the hobbit.",
    #     "Use an ability or item to persuade the hobbit to share the information without needing a meal.",
    #     "If you succeed in one of those, the hobbit is satisfied and gives you the information.",
    #     "Otherwise, the hobbit gets angry and starts attacking your hero for not providing a meal.",
    #     "To win this encounter, your hero must either:",
    # ],
    [
        "The Giant Chicken",
        "Your hero comes across a giant chicken blocking the path. It looks hungry and ready to attack.",
        "Have a Craftiness score higher than 16 to create a chicken costume and trick the giant chicken into thinking you are one of its own.",
        "Use an ability or item to distract the giant chicken and run away before it can attack.",
        "If you succeed in one of those, your hero manages to escape unharmed.",
        "Otherwise, the giant chicken pecks your hero and runs off with your backpack.",
        "To win this encounter, your hero must either:",
    ],
    # [
    #     "The Clumsy Assassin",
    #     "Your hero is targeted by an assassin who is trying to take them out.",
    #     "Have a Scrappiness score higher than 15 to disarm the assassin using improvised weapons.",
    #     "Use an ability or item to trip the assassin and knock them out.",
    #     "If you succeed in one of those, your hero manages to escape the assassin's grasp.",
    #     "Otherwise, the assassin catches your hero off guard and delivers a fatal blow.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Stampeding Herd",
    #     "Your hero encounters a large herd of cows stampeding towards them!",
    #     "Have a Scrappiness score higher than 13 to dodge the stampede and avoid getting trampled by the cows.",
    #     "Use an ability or item to distract the cows and prevent them from stampeding.",
    #     "If you succeed in one of those, then you are able to avoid getting trampled and move on.",
    #     "Otherwise, your hero gets caught up in the stampede and is trampled by the cows. They are left bruised and battered.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Cow Tipping",
    #     "Your hero sees a group of locals attempting to tip over a cow. They ask your hero to help!",
    #     "Have a Scrappiness score higher than 11 to successfully tip over the cow with the group.",
    #     "Use an ability or item to persuade the cow to lie down without tipping it over.",
    #     "If you succeed in one of those, then you are able to tip over the cow (or not) and move on.",
    #     "Otherwise, your hero falls over and is covered in cow manure. The locals laugh and your hero is left humiliated.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Dairy Farm",
    #     "Your hero finds themselves on a dairy farm with cows everywhere. The farmer needs your hero's help to milk the cows!",
    #     "Have a Craftiness score higher than 14 to successfully milk the cows.",
    #     "Use an ability or item to communicate with the cows and convince them to give up their milk.",
    #     "If you succeed in one of those, then you are able to milk the cows and move on.",
    #     "Otherwise, your hero is unable to milk the cows and is left with empty buckets.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Cow Auction",
    #     "Your hero comes across a cow auction and is asked to help auction off the cows.",
    #     "Have a Fabulousness score higher than 11 to successfully auction off the cows.",
    #     "Use an ability or item to hypnotize the cows and make them dance to sell them at a higher price.",
    #     "If you succeed in one of those, then you are able to auction off the cows and move on.",
    #     "Otherwise, your hero fails miserably and is left with unsold cows and a disappointed auctioneer.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Cow Whisperer",
    #     "Your hero comes across a cow that seems to be in distress. Can your hero help the cow?",
    #     "Have a Craftiness score higher than 13 to understand what the cow is saying and help it.",
    #     "Use an ability or item to sing a lullaby to the cow and put it to sleep.",
    #     "If you succeed in one of those, then you are able to help the cow and move on.",
    #     "Otherwise, your hero is unable to help the cow and is left feeling bad for it.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "Cow Stampede",
    #     "Your hero sees a herd of cows running towards them. The cows are heading straight for your hero and they must act quickly to avoid being trampled.",
    #     "Have a Scrappiness score higher than 11 to jump out of the way.",
    #     "Use an ability or item to scare the cows away.",
    #     "If you succeed in one of those, then you avoid being trampled and can continue on your way.",
    #     "Otherwise, you get run over by a cow and are knocked unconscious. When you wake up, you find yourself in a cow pasture.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "Milkmaid in Distress",
    #     "Your hero sees a milkmaid being harassed by a group of bandits. They are trying to steal her cow and milk.",
    #     "Have a Fabulousness score higher than 13 to talk the bandits out of it.",
    #     "Use an ability or item to distract the bandits.",
    #     "If you succeed in one of those, then you save the milkmaid and her cow and she rewards you with a bucket of fresh milk.",
    #     "Otherwise, the bandits attack you and you have to fight them off. The milkmaid gets away, but her cow is stolen.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "Cow Tipping",
    #     "Your hero and their friends decide to go cow tipping in the middle of the night. As you approach the sleeping cow, it suddenly wakes up and starts charging at you.",
    #     "Have a Sneakiness score higher than 11 to escape without being seen.",
    #     "Use an ability or item to distract the cow.",
    #     "If you succeed in one of those, then you escape without being trampled or caught by the farmer.",
    #     "Otherwise, you get caught by the farmer and have to spend the night in jail.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "Cow Poop",
    #     "Your hero is walking down a dirt path and steps in a large pile of cow poop. It's all over your boots!",
    #     "Have a Craftiness score higher than 14 to clean your boots off quickly and without making a mess.",
    #     "Use an ability or item to magically clean your boots.",
    #     "If you succeed in one of those, then you clean your boots off and continue on your way without any further mishaps.",
    #     "Otherwise, you slip and fall in more cow poop, ruining your outfit and dignity.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "Cow Costume",
    #     "Your hero comes across a group of cows who are having a party. They invite you to join, but you need to blend in.",
    #     "Have a Fabulousness score higher than 13 to create a convincing cow costume from materials on hand.",
    #     "Use an ability or item to magically transform into a cow.",
    #     "If you succeed in one of those, then you are able to join the party and have a great time with your new cow friends.",
    #     "Otherwise, the cows realize you are not a cow and they moo-stake you for a predator. They chase you out of the pasture and you end up covered in cow poop.",
    #     "To win this encounter, your hero must either:",
    # ],
    # [
    #     "The Slippery Bridge",
    #     "Your party comes across a rickety old bridge over a deep ravine. The bridge looks dangerous to cross.",
    #     "Use an ability or item to help you maintain balance while crossing the bridge.",
    #     "On the other side, you see a group of bandits waiting to ambush you. Use an ability or item to fight them off or escape past them.",
    #     "If you succeed, you make it across the bridge without incident and continue on your journey.",
    #     "Otherwise, you lose your footing and fall into the ravine below. You take significant damage and your party must use healing resources to revive you before continuing on your journey.  If you have no healing resources then you die.",
    #     "To win this encounter, your hero must survive both of the following:",
    # ],
    # [
    #     "The Locked Vault",
    #     "Your hero discovers a heavily secured vault rumored to contain great treasures. The vault's door is sturdy and protected by intricate mechanisms.",
    #     "Use an ability or item to pick the complex lock and gain access to the vault's riches.",
    #     "Inside the vault, a magical barrier blocks your path. Use an ability or item to dispel or bypass the barrier and claim the treasures within.",
    #     "If you succeed, the vault yields its secrets, and you acquire valuable treasures beyond your wildest dreams.",
    #     "However, if you fail, the lock resists your attempts, and the magical barrier repels your efforts. The vault remains sealed, denying you its treasures.",
    #     "To win this encounter, your hero must survive both of the following:",
    # ],
    [
        "The Charmed Audience",
        "Your hero finds themselves in front of a crowd eagerly awaiting a captivating performance in a talent show. The audience's expectations are high, and their attention hangs on your every word and action.",
        "Use an ability or item to charm and entertain the audience, leaving them spellbound by your charisma and stage presence.",
        "As your performance reaches its peak, a competitor attempts to sabotage you by dumping a giant container of lubricant all over the stage floor. Use an ability or item to overcome the slipperiness while maintaining the crowd's unwavering attention.",
        "If you succeed, the audience erupts in applause and showers you with adoration, granting you fame, admiration, and the rewards that come with it.",
        "However, if you fail, your performance falls flat, and the audience grows bored or even hostile. You leave the stage dejected, but with a valuable lesson in the fickleness of fame.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    # [
    #     "The Mystic Portal",
    #     "Your hero encounters a mystical portal shimmering with otherworldly energy. Its purpose and destination remain unknown.",
    #     "The portal requires power.  Use an ability or item to power up the portal and activate it, revealing its intended destination.",
    #     "Upon stepping through the portal, you find yourself falling towards a castle far below. Use an ability or item to survive the fall and land safely.",
    #     "If you succeed, you find yourself in a hidden castle of ancient treasures or profound knowledge.",
    #     "However, if you fail, the portal's secrets elude you, and you find yourself back at the entrance, bewildered and empty-handed.",
    #     "To win this encounter, your hero must survive both of the following:",
    # ],
    # [
    #     "The Enchanted Forest",
    #     "Your hero enters an enchanting forest filled with magical creatures and mystical energies. The air crackles with an otherworldly ambiance.",
    #     "Use an ability or item to communicate with the forest's magical inhabitants and gain their trust and guidance.",
    #     "As you delve deeper into the forest, you encounter a dense thicket blocking your path. Use an ability or item to navigate through the tangled foliage and reach your destination.",
    #     "If you succeed, the forest reveals its hidden secrets, granting you access to ancient knowledge or granting you a boon of magical power.",
    #     "However, if you fail, the forest's enchantments bewilder and disorient you, leaving you lost and vulnerable to its whims. You escape, but without the rewards you sought.",
    #     "To win this encounter, your hero must survive both of the following:",
    # ],
    [
        "The Cursed Relic",
        "Your hero comes across a mysterious relic shrouded in an aura of dark magic. Its malevolent energy pulses with an unsettling presence.",
        "Use an ability or item to dispel or contain the relic's cursed magic, freeing it from its evil influence.",
        "As you attempt to handle the relic, it unleashes a wave of dark energy, summoning spectral guardians to protect itself. Use an ability or item to vanquish these otherworldly sentinels and claim the relic.",
        "If you succeed, you neutralize the relic's curse and gain control over its potent power, enabling you to wield it for your own purposes.",
        "However, if you fail, the relic's curse overwhelms you, binding you to its malevolence. You discard the relic, your mind tainted by its dark magic.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    # [
    #     "The Haunted Manor",
    #     "Your hero arrives at an eerie, dilapidated manor said to be haunted by vengeful spirits. The air is heavy with a sense of dread and despair.",
    #     "Use an ability or item to communicate with the restless spirits and uncover the truth behind their suffering, offering them solace and closure.",
    #     "As you delve deeper into the manor, the spirits manifest their rage, launching ethereal attacks to repel intruders. Use an ability or item to fend off these spectral assaults and progress further.",
    #     "If you succeed, you lay the spirits to rest, bringing peace to the haunted manor and uncovering hidden treasures or forgotten secrets.",
    #     "However, if you fail, the spirits' anger overwhelms you, forcing you to flee the manor, shaken and empty-handed.",
    #     "To win this encounter, your hero must survive both of the following:",
    # ],
    [
        "The Forbidden Library",
        "Your hero stumbles upon a hidden library of forbidden knowledge, its shelves lined with ancient tomes and arcane manuscripts.",
        "Use an ability or item to unravel the complex magical wards guarding the library's entrance, granting you access to its forbidden wisdom.",
        "Inside the library, a spirit Fox-Librarian manifests, demanding a payment for usage of the library. Use an ability or item to bribe the librarian.",
        "If you succeed, the library opens its vast trove of esoteric knowledge to you, allowing you to learn powerful spells or gain profound insights.",
        "However, if you fail, the library's wards repel your intrusion, sealing its secrets from your grasp. You leave empty-handed, but with a lingering curiosity for the forbidden knowledge within.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Crystal Cavern",
        "Your hero discovers a hidden cavern sparkling with mesmerizing crystals of various colors and sizes. The air is filled with a gentle hum of energy.",
        "Use an ability or item to attune yourself to the crystals' vibrations and harness their magical properties for your benefit.",
        "As you explore deeper into the cavern, you encounter a network of treacherous crystal formations. Use an ability or item to navigate through the hazardous terrain and reach the heart of the cavern.",
        "If you succeed, the crystals bestow upon you their gifts, enhancing your abilities or granting you a newfound affinity for magic.",
        "However, if you fail, the crystals' energies overwhelm you, disorienting your senses and leaving you lost in the labyrinthine depths of the cavern. You emerge, unharmed but empty-handed.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Fey Crossing",
        "Your hero discovers a hidden pathway leading to the realm of the fey, a place of whimsical enchantment and unpredictable magic.",
        "Use an ability or item to charm and befriend the mischievous fey creatures, gaining their trust and unlocking their hidden knowledge or favors.",
        "As you traverse the fey realm, you encounter a captivating fey guardian who challenges you to a race across a forest. Use an ability or item to outwit the guardian and emerge victorious.",
        "If you succeed, the fey realm reveals its secrets, offering you magical artifacts or granting you the ability to summon the aid of the fey in times of need.",
        "However, if you fail, the fey guardian's riddles confound you, and you are politely escorted back to the mortal realm, empty-handed but enchanted by the encounter.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Trials of the Elements",
        "In the realm of magical spirit journeys, you encounter a series of elemental trials that test your connection to the forces of nature.",
        "The first trial is the Trial of Fire, where you must use an ability or item to withstand scorching flames and prove your resilience.",
        "Next, you face the Trial of Water, where you must use an ability or item to breathe underwater and swim through a turbulent current.",
        "If you succeed in both elemental trials, the spirits reveal the location of the sacred grove, where ancient knowledge awaits your discovery.",
        "However, if you fail to withstand the flames or swim through the currents, the elemental spirits deem you unworthy, and the secrets of the sacred grove remain hidden.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Spirit Guardian",
        "Your hero embarks on a magical spirit journey to seek the wisdom of ancient spirits. As you traverse through the ethereal realm, you encounter a powerful spirit guardian who demands a worthy offering.",
        "Use an ability or item to present a valuable gift that appeases the guardian and earns their guidance and knowledge.",
        "To prove yourself, you must cross a treacherous chasm bridged by floating platforms. Use an ability or item to navigate the platforms and reach the other side safely.",
        "If you succeed in both challenges, the spirit guardian shares their profound wisdom, providing insights and revelations beyond mortal comprehension.",
        "However, if you fail to satisfy the guardian's demands or fall into the chasm, the guardian deems you unworthy of their wisdom, and your spirit journey comes to an end.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Shadow Behemoth",
        "Your hero ventures into the depths of the underworld and comes face to face with the terrifying Shadow Behemoth, a colossal creature of darkness and despair.",
        "Use an ability or item to evade the Behemoth's relentless pursuit and escape its clutches.",
        "As you navigate deeper into the underworld, you encounter a labyrinth of twisted passages. Use an ability or item to find the correct path and avoid the traps set by the Behemoth.",
        "If you succeed in both challenges, you manage to outwit and elude the Shadow Behemoth, escaping its wrath and continuing your journey.",
        "However, if you fail to escape its pursuit or fall into the Behemoth's traps, you become trapped in its darkness, consumed by its malevolent presence.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Stygian Serpent",
        "Within the depths of the underworld, you encounter the monstrous Stygian Serpent, a legendary creature of venom and cunning.",
        "Use an ability or item to resist the Serpent's venomous attacks and prevent its deadly poison from overtaking your body.",
        "As the battle with the Serpent intensifies, it summons a swirling vortex of darkness. Use an ability or item to maintain your footing and resist being pulled into the abyss.",
        "If you succeed in both challenges, you emerge victorious over the Stygian Serpent, vanquishing its threat and claiming a fragment of its power.",
        "However, if you succumb to the Serpent's venom or get consumed by the vortex of darkness, your spirit is lost in the underworld, forever trapped in its depths.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Infernal Golem",
        "As you delve into the underworld, you confront the hulking Infernal Golem, a formidable construct fueled by the fiery essence of the underworld.",
        "Use an ability or item to withstand the Golem's relentless onslaught of flames and resist being incinerated by its blazing attacks.",
        "Within the fiery chamber where the Golem resides, you encounter a series of molten lava streams. Use an ability or item to navigate the treacherous terrain and cross to the other side.",
        "If you succeed in both challenges, you emerge triumphant over the Infernal Golem, harnessing its fiery energy and unlocking newfound power.",
        "However, if you cannot withstand the Golem's flames or succumb to the molten lava, your body is consumed by the inferno, leaving nothing but ashes behind.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Venomous Depths",
        "Your party ventures into the treacherous Venomous Depths, a network of caves infested with deadly creatures and poisonous flora.",
        "Use an ability or item to detect and evade the venomous creatures lurking in the shadows, avoiding their deadly strikes.",
        "As you progress through the caves, you stumble upon a venomous plant with valuable medicinal properties. Use an ability or item to extract its antidote while avoiding its toxic defenses.",
        "If you succeed in both challenges, you harness the healing properties of the venomous plant and emerge from the Venomous Depths with newfound resilience and antidotes.",
        "However, if you fall victim to the venomous creatures or fail to extract the antidote, the Venomous Depths claim their victims, leaving your party weakened and vulnerable to the dangers that lie ahead.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Goblin Heist",
        "Your party learns of a goblin heist taking place in the heart of the town. The goblins plan to steal a precious artifact from a heavily guarded building.",
        "Use an ability or item to infiltrate the guarded building, bypassing traps and security measures set up by the goblins.",
        "Inside the building, you confront the goblin leader who holds the artifact. Use an ability or item to defeat the goblin leader and retrieve the stolen artifact.",
        "If you succeed in both challenges, you thwart the goblin heist, recover the artifact, and restore peace to the town.",
        "However, if you trigger the traps or fail to defeat the goblin leader, the heist succeeds, and the town suffers the consequences of the goblins' actions.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Underground Concert",
        "Your party stumbles upon an underground concert organized by a group of crust-punks. The venue is filled with pulsating music, rebellious energy, and an atmosphere of freedom.",
        "Use an ability or item to immerse yourself in the concert, dancing and connecting with the crust-punks on a deep level.",
        "As the concert reaches its climax, a rival gang storms the venue, seeking to cause mayhem and assert dominance. Use an ability or item to protect the band and the crowd from harm.",
        "If you succeed in both challenges, you gain the respect and admiration of the crust-punks, forming bonds and potentially unraveling secrets within their underground network.",
        "However, if you fail to embrace the concert's spirit or cannot fend off the rival gang, your party may be seen as outsiders or even face retaliation from the crust-punks.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Crust-Punk Hideout",
        "Your party stumbles upon a hidden den inhabited by a group of unruly crust-punks. They are known for their rowdy behavior, anarchist ideologies, and disregard for authority.",
        "Use an ability or item to navigate through the chaotic hideout, avoiding confrontations and staying off the crust-punks' radar.",
        "As you explore further into the den, you come across the crust-punk leader who challenges your party to a test of strength. Use an ability or item to defeat the leader in a physical contest.",
        "If you succeed in both challenges, you earn the respect of the crust-punks and potentially gain valuable information or assistance from their network.",
        "However, if you get caught up in conflicts within the hideout or fail to defeat the leader, your party may face hostility or be expelled from the den.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Crust-Punk Challenge",
        "Your party is challenged by a group of crust-punks to prove your worth and dedication to their lifestyle and beliefs.",
        "Use an ability or item to showcase your survival skills and resourcefulness in an urban environment, impressing the crust-punks with your grit and adaptability.",
        "As you gain their initial acceptance, the crust-punks propose a graffiti competition to test your artistic prowess. Use an ability or item to create a striking graffiti piece that reflects their ideals.",
        "If you succeed in both challenges, you earn the trust and acceptance of the crust-punks, potentially gaining access to their community and valuable information.",
        "However, if you struggle to demonstrate your survival skills or fail to create an impactful graffiti piece, your party may be seen as outsiders or even face disdain from the crust-punks.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Snowy Pass",
        "Your party ventures into a treacherous mountain pass blanketed in deep snow. The area is known for its ferocious beasts that lurk in the icy wilderness.",
        "Use an ability or item to navigate through the snow-covered terrain, avoiding treacherous slopes and hidden dangers.",
        "As you ascend further, a pack of territorial snow wolves emerges from the shadows, ready to defend their territory. Use an ability or item to either calm the wolves or defeat them in combat.",
        "If you succeed in both challenges, you safely traverse the snowy pass and may even acquire valuable resources or knowledge about the mountain range.",
        "However, if you struggle with the treacherous terrain or fail to overcome the snow wolves, your party may face harsh weather conditions or become targets for other dangerous creatures lurking in the mountains.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Frozen Cavern",
        "Your party stumbles upon a frozen cavern hidden deep within the icy mountains. The cavern is rumored to house rare treasures, but it is also home to formidable creatures.",
        "Use an ability or item to navigate through the frigid tunnels, avoiding frozen pitfalls and deadly stalactites.",
        "As you delve deeper into the cavern, a massive ice elemental awakens, determined to protect its domain. Use an ability or item to weaken the elemental's icy defenses and defeat it.",
        "If you succeed in both challenges, you uncover the hidden treasures within the cavern, securing valuable artifacts or magical items.",
        "However, if you struggle with the hazardous environment or fail to overcome the ice elemental, your party may become trapped in the frozen depths or suffer from frostbite and exhaustion.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Avalanche Threat",
        "Your party must traverse a narrow mountain path prone to frequent avalanches. The snow-covered slopes are home to powerful yet territorial creatures that guard their territory.",
        "Use an ability or item to carefully navigate the unstable path, avoiding triggering an avalanche or falling into hidden crevasses.",
        "As you progress, a massive yeti blocks your way, bellowing with territorial rage. Use an ability or item to either appease the yeti or defeat it in a battle of strength.",
        "If you succeed in both challenges, you overcome the avalanche threat and the yeti encounter, allowing your party to continue their journey through the mountains.",
        "However, if you struggle to maintain your footing on the treacherous path or fail to pacify the yeti, your party may be swept away by an avalanche or forced to retreat from the mountains.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Blizzard's Wrath",
        "Your party finds themselves caught in the midst of a fierce blizzard, with howling winds and blinding snow reducing visibility to a mere few feet.",
        "Use an ability or item to navigate through the blizzard, staying together and avoiding dangerous cliffs or falling into hidden ravines.",
        "As the blizzard rages on, a group of territorial snow trolls appears, seeking shelter from the storm. Use an ability or item to negotiate with the trolls or defeat them in combat.",
        "If you succeed in both challenges, you survive the blizzard's wrath and potentially gain the trolls' aid or knowledge about navigating the treacherous mountain peaks.",
        "However, if you struggle to endure the blizzard's harsh conditions or fail to overcome the snow trolls, your party may suffer from frostbite, hypothermia, or become disoriented in the storm.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Enchanted Oasis",
        "Your party ventures into a barren desert, seeking refuge from the scorching sun. In the distance, you spot an oasis surrounded by peculiar cacti known for their hallucinogenic properties.",
        "Use an ability or item to navigate the treacherous desert sands, avoiding dangerous sinkholes and scorching hot patches.",
        "As you approach the oasis, the air becomes thick with hallucinogenic pollen released by the enchanted cacti. Use an ability or item to resist the hallucinatory effects and maintain your focus.",
        "If you succeed in both challenges, you find solace within the oasis, quenching your thirst and potentially discovering hidden treasures or secrets.",
        "However, if you struggle with the harsh desert conditions or fail to resist the hallucinations, your party may wander aimlessly, succumb to dehydration, or experience vivid and unpredictable hallucinatory episodes.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Lost Sheep",
        "While traversing the vast prairie, your party stumbles upon a lost sheep separated from its flock. The sheep looks distressed and vulnerable to the dangers of the wilderness.",
        "Use an ability or item to gain the trust of the lost sheep and guide it back to its flock, ensuring its safety and well-being.",
        "As you search for the sheep's flock, you encounter a wolf that sees the lost sheep and starts stalking it. Use an ability or item to defuse the situation and protect the defenseless creature.",
        "If you succeed in both challenges, you reunite the lost sheep with its flock and earn the gratitude of the shepherd, who rewards you with magical items.",
        "However, if you struggle to win the trust of the lost sheep or fail to pacify the territorial farm animal, the sheep does not make it and your party failed to save an innocent creature.  -1 Fabulousness",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Dragon's Lair",
        "Your party embarks on a daring quest to slay a fearsome dragon that terrorizes nearby villages. As you approach the dragon's lair, you notice that the dragon is gone but go inside to investigate.",
        "Inside, there are sleeping young wyverns in the first cavern.  Use an ability or item to stealthily navigate past the wyverns.",
        "As you venture deeper into the lair, you encounter a fairy trapped in a metal cage who offers you crucial information about the dragon's weaknesses if you can free them. Use an ability or item to free the fairy and gain their assistance.",
        "If you succeed in both challenges, you gain with newfound knowledge against your future dragon battle, increasing your chances of victory and earning the admiration of the fairy tale creature you rescued.",
        "However, if you fail to navigate the dragon's lair undetected or cannot free the captive fairy, your party is injured escaping the cavern and must receive a punishment.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Sleeping Beauty",
        "In your travels, you come across a secluded cottage hidden deep within the woods, where a mysterious slumbering beauty lies in an eternal sleep. The cottage is guarded by mythical creatures and shrouded in enchantment.",
        "Use an ability or item to gain the trust of the mythical creatures guarding the cottage, convincing them that you mean no harm.",
        "As you approach the slumbering beauty, you encounter a powerful curse that prevents her from waking. Use an ability or item to break the curse and awaken the sleeping beauty.",
        "If you succeed in both challenges, the sleeping beauty awakens, and her gratitude rewards your party with magical artifacts and a glimpse into the secrets of the enchanted realm.",
        "However, if you struggle to gain the trust of the mythical creatures or fail to break the curse, the sleeping beauty remains trapped, and the cottage becomes more perilous, potentially leading to your party's entrapment or falling victim to the curse.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Fairy Circle",
        "While traversing a lush meadow, your party stumbles upon a magical fairy circle. The ethereal beings dance and frolic, their presence infusing the air with an otherworldly glow.",
        "Use an ability or item to respectfully interact with the fairies, gaining their trust and proving that you mean no harm.",
        "As you engage with the fairies, they invite you to participate in a whimsical dance. Use an ability or item to match the grace and rhythm of the fairies' dance.",
        "If you succeed in both challenges, the fairies bless your party with their magic, enhancing your abilities or granting you temporary enchantments to aid you on your journey.",
        "However, if you struggle to gain the fairies' trust or fail to keep up with their dance, they may become hostile, leading to a loss of their blessings or even facing their wrath for disrespecting their circle.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Fairy Godmother's Test",
        "Your party encounters a mysterious old woman who claims to be a powerful fairy godmother. She offers to grant you a single wish, but first, you must prove your worthiness through a series of challenges.",
        "Use an ability or item to showcase your kindness and compassion, demonstrating that you will use the granted wish for a noble cause.",
        "The fairy godmother then presents you with a challenge: Climb the great Deku tree and harvest some of its nuts. Use an ability or item to overcome the challenge and impress the fairy godmother.",
        "If you succeed in both challenges, the fairy godmother rewards your party with a powerful magical prize.",
        "However, if you struggle to display kindness or fail to meet the fairy godmother's challenge, you suffer her punishments.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Mermaid's Song",
        "While sailing across a vast ocean, your party encounters a group of mesmerizing mermaids singing hauntingly beautiful melodies. Their songs have the power to enchant and enthrall any who listen.",
        "Use an ability or item to resist the enchanting song of the mermaids, maintaining your focus and avoiding falling under their spell.",
        "As you approach closer, a mischievous water sprite changes the ocean currents to push your boat towards rocks! Use an ability or item to outwit the sprite and save your boat.",
        "If you succeed in both challenges, the mermaids recognize your resilience and offer their assistance, guiding you safely through treacherous currents or revealing the location of a hidden underwater treasure.",
        "However, if you succumb to the mermaids' song or fall prey to the water sprite's trickery, your party may face dire consequences, losing control of your ship and being dragged into the depths of the ocean.",
        "To win this encounter, your hero must survive both of the following:",
    ],
    [
        "The Magical Menagerie",
        "Your party stumbles upon a hidden sanctuary filled with extraordinary creatures from myth and legend. Majestic unicorns, playful griffins, and elusive phoenixes roam freely in this enchanted refuge.",
        "Walking through a meadow, you find an injured unicorn with a bear trap on its leg.  Use an ability or item to rescue the unicorn from the trap and heal it.",
        "The unicorn tells you that a mischievous troll has infiltrated, causing chaos and disturbing the delicate balance. Use an ability or item to outwit and defeat the troll and restore harmony to the sanctuary.",
        "If you succeed in both challenges, the magical creatures reward your party with rare treasures, mystical insights, and even the opportunity to ride upon their backs for a brief time.",
        "However, if you fail to save the unicorn or fail to subdue the troll, the sanctuary becomes a chaotic and dangerous place, and your party may be forced to retreat from the wrath of the magical inhabitants. ",
        "To win this encounter, your hero must survive both of the following:",
    ],
]


class Encounter(object):
    title = ""
    prompt = ""
    option_a = ""
    option_b = ""
    pos_result = ""
    neg_result = ""
    connecting_phrase = ""

    def __init__(self):
        encounter = random.choice(ENCOUNTERS)
        self.title = encounter[0]
        self.prompt = encounter[1]
        self.option_a = encounter[2]
        self.option_b = encounter[3]
        self.pos_result = encounter[4]
        self.neg_result = encounter[5]
        self.connecting_phrase = encounter[6]

    def __str__(self):
        return f"{self.title}: {self.prompt}  Either: {self.option_a} OR {self.option_b} {self.pos_result} {self.neg_result}"
